# permissions for end users to edit timescalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: timescaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go-operator-sample
    app.kubernetes.io/part-of: go-operator-sample
    app.kubernetes.io/managed-by: kustomize
  name: timescaler-editor-role
rules:
- apiGroups:
  - autoscaling.example.com
  resources:
  - timescalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.example.com
  resources:
  - timescalers/status
  verbs:
  - get
